loom.platform=forge
org.gradle.jvmargs=-Xmx4G "-XX:MaxMetaspaceSize=384m"
org.gradle.internal.http.connectionTimeout=120000
org.gradle.internal.http.socketTimeout=120000
org.gradle.daemon=false

version = v2.21.22-2501
lunarVersion = v2.21.22-2501
lunarGitCommit = 60efb3f2e372081255caeefab481a9ad69f3820b