loom.platform=forge
org.gradle.jvmargs=-Xmx4G "-XX:MaxMetaspaceSize=384m"
org.gradle.internal.http.connectionTimeout=120000
org.gradle.internal.http.socketTimeout=120000
org.gradle.daemon=false

version = v2.21.23-2602
lunarVersion = v2.21.23-2602
lunarGitCommit = 2ba92354f2b1f38d040e3fe5d9caf65640e3b3a0