loom.platform=forge
org.gradle.jvmargs=-Xmx4G "-XX:MaxMetaspaceSize=384m"
org.gradle.internal.http.connectionTimeout=120000
org.gradle.internal.http.socketTimeout=120000
org.gradle.daemon=false

version = 69617b1/dev
lunarVersion = 69617b1/dev
lunarGitCommit = 69617b1b9b1719988b66fc4325b0e3c5152e72b1